### ISSUE TITLE
Free Software friendly flashing instructions 

### ISSUE THREAD

**Issue by endian-albin** [endian-albin/pinetime-hypnos#38]
Add instructions for how to install the firmware using OpenOCD with a suitable single-board computer, e.g. the Beagle Bone Black.

**Comment by jlukanc1** [comment]
lupyuen`s [OpenOCD-spi](https://github.com/lupyuen/openocd-spi) might be useful, it is made for Raspberry Pi.

**Comment by endian-albin** [comment]
Thanks! I'll look into it. I personally won't use a Pi because I don't own one and it depends on blobs.

**Comment by endian-albin** [comment]
I rename this issue because the most important thing is to make a free software flashing method the default. The programmer used is secondary.
