### ISSUE TITLE
[feature] interact with the display

### ISSUE THREAD

**Issue by sdorre** [endian-albin/pinetime-hypnos#55]
I saw that we are using the lvgl as a graphic library am I right ? 

It would be nice to implement some kind of interraction with the display at some point. 

I found that page:
https://github.com/lvgl/lvgl/blob/069e24bdb294f27cc45c50497b05b5377d9f16d7/examples/porting/lv_port_indev_template.c
Unfortunately, it seems like the library is not interrupt based. It implements simply a periodic read of the x and y coordinates and make the use of that. 

We still could based the touch controller on interrupt and save the coordinate somewhere. And give those value to the read callback of the library ? 

What do you think ?

Documentation about  input devices in lvgl: 
https://docs.lvgl.io/v7/en/html/porting/indev.html?highlight=lv_indev_state_rel#

**Comment by endian-albin** [comment]
Yes, I think the way to do this is to call the function that reads the coordinates inside the touch ISR somehow. It may be necessary to put the actual reading in thread though, to avoid crashes. [najnesnaj](https://github.com/najnesnaj/pinetime-zephyr) has a sample for reading coordinates with LVGL but it only works without interrupts. The touch driver has two options: "own thread" and "global thread". I've only managed to make touch interrupts work with the latter.

**Comment by endian-albin** [comment]
With the new touch driver in place, it would be nice to add a new "version info /credits" screen that you get to by swiping.
