### ISSUE TITLE
Enable logging only when needed

### ISSUE THREAD

**Issue by endian-albin** [endian-albin/pinetime-hypnos#8]
We currently use `printk()` or `printf()` for debug output. We should really switch to something like `LOG_DBG` and `LOG_INF though` to have better control. 

From a power-management standpoint it also makes sense to build different sets of images (debug/production) where JLink logging, etc. are either enabled or disabled. This can be done from cmake I think. From the [PineTime wiki](https://wiki.pine64.org/index.php/PineTime#How_to_write_battery_friendly_software.3F):

```
Do not use logging (JLink RTT, SWO, semihosting,...), it uses a lot of power.
```

**Comment by Lukas-Berglund** [comment]
Okay, I can take a closer look at this. I think we can use a script to run Cmake with different parameters depending on if debugging should be enabled or not.

**Comment by endian-albin** [comment]
I reopened the issue since only the first part has been done.

**Comment by endian-albin** [comment]
I've now completed the second part.
