### ISSUE TITLE
Upgrade to Zephyr v2.4.0

### ISSUE THREAD

**Issue by endian-albin** [endian-albin/pinetime-hypnos#85]
A new upstream release is on its way and I've started porting stuff from v2.3.0 to v2.4.0-rc1. The main reason for doing it this early is to get to the new LVGLv7 before doing any more GUI-related work.

I just got stuck at a number of errors and warnings around the cst816s touch controller, however. @sdorre, would you be interested in trying to get your driver up to date with the latest zephyr? If so, you could checkout and try to build the `upgrade-to-zephyr-v2.4.0` branch that I've pushed.

**Comment by endian-albin** [comment]
I couldn't keep away from the touch driver and did make some "arbitrary" changes after looking at the [changes performed upstream](https://github.com/zephyrproject-rtos/zephyr/commit/d00d86972a13cd38f3dc9fdfa1ab5a2b755812c2). The compiler doesn't complain at least.

**Comment by endian-albin** [comment]
I get correct debug output, touch events are registered, backlight works, but the screen stays black at the moment.

**Comment by endian-albin** [comment]
I've got everything working except BLE right now.

**Comment by endian-albin** [comment]
Fixed SMP as well. Creating a PR.

**Comment by sdorre** [comment]
Button and charging detection are not working on my side. Is that a known issue ?

**Comment by endian-albin** [comment]
Oh, they are working on my end. You're not running a P8 build, are you?
