### ISSUE TITLE
P8 jedec

### ISSUE THREAD

**Issue by tt1pjm** [endian-albin/pinetime-hypnos#87]
I've tested latest P8 firmware via DFU with MCUBoot and no issues to report. The values stored in P8.dts (jedec-id = [0b 40 16]) do not seem to impact function. I needed to use jedec-id = [20 40 16] for MCUboot to work. Issue can be closed.

**Comment by endian-albin** [comment]
I don't understand. Did it work or not with the existing jedec-values in p8.dts? If you needed to change them, then I suppose I should do the same, because the only reason they are currently the same as on the pinetime is because I copied the values without testing.

**Comment by tt1pjm** [comment]
I uploaded Hypnos to P8 using DFU but didn't then test DFU while Hypnos was running on P8. I'm guessing that's where the dependency on the P8 jedec values is, please confirm and I'll run another test. I only validated that Hypnos runs on my first test as I wasn't sure where the dependency on jedec values was.

**Comment by endian-albin** [comment]
Ah, then I understand. Could you please try out [this P8 package](https://github.com/endian-albin/pinetime-hypnos/suites/1251546077/artifacts/19065586) and see if you can successfully perform DFU? I set the jedec-id to [20 40 16].

**Comment by tt1pjm** [comment]
I could DFU the package from Infinitime and seemed ok on screen. I could connect from RFConnect to try DFU. Not sure whether I caused a restart or there was a crash that caused a restart back to Infinitime. I tried the same on v0.1.0-8 and could connect from RFConnect. When selecting DFU it asked me to choose a *.bin file and "Test & Confirm", "Test" or "Confirm". I used the bin file from the package and all 3 options caused a rollback to Infinitime.

**Comment by endian-albin** [comment]
So you could install p8-hypnos-v0.1.0-2-g7c50e3c over nRFConnect and it started OK, but when you reconnected with nRFConnect it rebooted and reverted to InfiniTime?

(0.1.0-8 will not work since it doesn't contain the updated jedec values. It will probably crash when trying to write to SPI flash.)

Could you please install p8-hypnos-v0.1.0-2-g7c50e3c again and then flash the **bin** file contained in the InfiniTime package from nRF connect? Hypnos can be installed from e.g. InfiniTime using DFU zip packages, but can only perform new updates using bin files.

**Comment by tt1pjm** [comment]
I could install p8-hypnos-v0.1.0-2-g7c50e3c over nRFConnect and it started OK. When I try to connect from nRFConnect after install it fails during service discovery and remains disconnected. After what seems to be a variable amount of time, the watch will restart and restores Infinitime. In further tests I've been unable to create the same as result as prior where I could attempt to DFU a bin file for test/confirm.

**Comment by endian-albin** [comment]
Okay, that's unfortunate. Well, it's good that it restores the previous image at least :-)

Thanks for trying. I'll leave this issue open.

**Comment by endian-albin** [comment]
Oh, could you please try one more image, @tt1pjm? I just upgraded to Zephyr v2.4.0 and built [p8-hypnos-v0.1.0-10-gdc5c409-mcuboot-app-dfu](https://github.com/endian-albin/pinetime-hypnos/suites/1255078846/artifacts/19159267). If you still run into issues, we'll let this case rest for a while.

**Comment by tt1pjm** [comment]
OK, that's much better. Completed DFU update using nRFConnect from Infinitime to  p8-hypnos-v0.1.0-10-gdc5c409, then confirmed using bin file. Then DFU (Test and Confirm) from p8-hypnos-v0.1.0-10-gdc5c409 back to Infinitime. So this confirms the jedec change works.
SPI flash on my P8 is XMC - XM25QH32B. I don't know if it's the same across all P8s, there are different suppliers.

**Comment by endian-albin** [comment]
Nice! I'll merge this change then. If someone reports having issues due to slightly different hardware components, we'll deal with them then.
